// ==========================================
// RIS SHARED HELPERS
// ==========================================

const RIS_ENTRIES_DEFAULT_HEADERS = [
  'Timestamp', 'RIS Number', 'Date Requested', 'Requestor Program', 'Requestor Email',
  'Delivery Location / Office', 'Requested By', 'Approved By', 'Issued By', 'Received By',
  'Purpose', 'Grand Total', 'Category', 'Inventory Source', 'RIS Status', 'PDF URL',
  'PDF Generated Date', 'PDF Generated By', 'Excel URL', 'Excel Generated Date', 'Excel Generated By'
];

const RIS_ENTRIES_FIELD_ORDER = [
  'timestamp', 'recordId', 'risNo', 'deliveryDate', 'requestorProgram', 'requestorEmail',
  'deliveryLocation', 'requestedBy', 'approvedBy', 'issuedBy', 'receivedBy', 'purpose',
  'grandTotal', 'category', 'inventorySource', 'risStatus', 'pdfUrl', 'pdfGeneratedAt',
  'pdfGeneratedBy', 'excelUrl', 'excelGeneratedAt', 'excelGeneratedBy'
];

const RIS_ENTRIES_ALIASES = {
  timestamp: ['Timestamp', 'Date Submitted', 'Submitted At'],
  recordId: ['Record ID', 'RecordId'],
  risNo: ['RIS Number', 'RIS No.', 'RIS No'],
  deliveryDate: ['Date Requested', 'Date', 'Delivery Date', 'RIS Date'],
  requestorProgram: ['Requestor Program', 'Program', 'End User'],
  requestorEmail: ['Requestor Email', 'Email', 'Email Address'],
  deliveryLocation: ['Delivery Location / Office', 'Delivery Location', 'Office'],
  requestedBy: ['Requested By'],
  approvedBy: ['Approved By'],
  issuedBy: ['Issued By'],
  receivedBy: ['Received By'],
  purpose: ['Purpose'],
  grandTotal: ['Grand Total', 'Total Request Amount', 'Total Amount'],
  category: ['Category', 'RIS Category'],
  inventorySource: ['Inventory Source', 'Source', 'Source Sheet', 'RIS Button Name'],
  risStatus: ['RIS Status', 'Status'],
  pdfUrl: ['PDF URL', 'RIS PDF URL', 'PDF Link'],
  pdfGeneratedAt: ['PDF Generated Date', 'PDF Generated At', 'RIS PDF Generated At'],
  pdfGeneratedBy: ['PDF Generated By', 'RIS PDF Generated By'],
  excelUrl: ['Excel URL', 'RIS Excel URL', 'Excel Link'],
  excelGeneratedAt: ['Excel Generated Date', 'Excel Generated At', 'RIS Excel Generated At'],
  excelGeneratedBy: ['Excel Generated By', 'RIS Excel Generated By']
};

const RIS_ITEMS_DEFAULT_HEADERS = [
  'Timestamp', 'Item ID', 'RIS Number', 'Item Description', 'Item Code', 'UOM',
  'PO/PTR Number', 'Batch / Lot No.', 'Supplier', 'Expiry Date', 'Current SOH',
  'Qty Requested', 'Issued Qty', 'Unit Cost', 'Total Cost', 'Remarks', 'Category',
  'Inventory Source', 'Source Sheet', 'Source Row', 'Source Spreadsheet ID', 'Source Header Row'
];

const RIS_ITEMS_FIELD_ORDER = [
  'timestamp', 'itemId', 'recordId', 'risNo', 'itemDescription', 'itemCode', 'uom',
  'poNumber', 'batch', 'supplier', 'expiry', 'currentSoh', 'qtyRequested', 'issuedQty',
  'unitCost', 'totalCost', 'remarks', 'category', 'inventorySource', 'sourceSheet',
  'sourceRow', 'sourceSpreadsheetId', 'sourceHeaderRow'
];

const RIS_ITEMS_ALIASES = {
  timestamp: ['Timestamp', 'Date Submitted', 'Submitted At'],
  itemId: ['Item ID', 'ItemId'],
  recordId: ['Record ID', 'RecordId'],
  risNo: ['RIS Number', 'RIS No.', 'RIS No'],
  itemDescription: ['Item Description', 'Description'],
  itemCode: ['Item Code'],
  uom: ['UOM', 'Unit of Measure', 'Unit of Measurement'],
  poNumber: ['PO/PTR Number', 'PO / PTR', 'PO / PTR Number', 'Purchase Order Number', 'PO Number'],
  batch: ['Batch / Lot No.', 'Batch / Lot No', 'Batch', 'Lot Number', 'Batch / Lot Number'],
  supplier: ['Supplier'],
  expiry: ['Expiry Date', 'Expiration Date'],
  currentSoh: ['Current SOH', 'Stock On Hand', 'SOH', 'Stock Available', 'Physical Count'],
  qtyRequested: ['Qty Requested', 'Quantity Requested', 'Qty Req'],
  issuedQty: ['Issued Qty', 'Issued Quantity'],
  unitCost: ['Unit Cost'],
  totalCost: ['Total Cost', 'Total Amount', 'Total Price'],
  remarks: ['Remarks'],
  category: ['Category', 'RIS Category'],
  inventorySource: ['Inventory Source', 'Source'],
  sourceSheet: ['Source Sheet', 'Inventory Source Sheet'],
  sourceRow: ['Source Row', 'Inventory Source Row'],
  sourceSpreadsheetId: ['Source Spreadsheet ID'],
  sourceHeaderRow: ['Source Header Row']
};

function risCoreGetTransactionsSpreadsheet_() {
  if (RIS_CONFIG.transactionsSheetId && RIS_CONFIG.transactionsSheetId.indexOf('PASTE_') !== 0) {
    return SpreadsheetApp.openById(RIS_CONFIG.transactionsSheetId);
  }
  return SpreadsheetApp.getActiveSpreadsheet();
}

function risCoreOpenSourceSpreadsheet_(source) {
  const sourceId = source && source.sourceSpreadsheetId && source.sourceSpreadsheetId !== 'same'
    ? source.sourceSpreadsheetId
    : RIS_CONFIG.inventorySheetId;
  if (sourceId && sourceId.indexOf('PASTE_') !== 0) return SpreadsheetApp.openById(sourceId);
  return risCoreGetTransactionsSpreadsheet_();
}

function risCoreEnsureTransactionSheets_(ss, createMissingSheets) {
  const create = createMissingSheets !== false;
  const entriesSheet = risCoreGetConfiguredSheet_(ss, RIS_CONFIG.entriesSheetName, create);
  const itemsSheet = risCoreGetConfiguredSheet_(ss, RIS_CONFIG.itemsSheetName, create);
  const holidaysSheet = risCoreGetConfiguredSheet_(ss, RIS_CONFIG.holidaysSheetName, create);
  risCoreEnsureEmailSheets_(ss, create);

  if (!create) return;

  risCoreEnsureColumns_(entriesSheet, RIS_ENTRIES_DEFAULT_HEADERS);
  risCoreEnsureColumns_(itemsSheet, RIS_ITEMS_DEFAULT_HEADERS);
  risCoreEnsureColumns_(holidaysSheet, ['Date', 'Holiday Name']);
}

function risCoreEnsureEmailSheets_(ss, createMissingSheets) {
  const create = createMissingSheets !== false;
  const adminSheet = risCoreGetConfiguredSheet_(ss, RIS_CONFIG.adminEmailsSheetName, create);
  const clientSheet = risCoreGetConfiguredSheet_(ss, RIS_CONFIG.clientEmailsSheetName, create);

  if (!create) return;

  risCoreEnsureColumnsByAliases_(adminSheet, [
    { header: 'Recipients', aliases: ['Recipients', 'Receipients', 'Recipient', 'Email', 'Email Address', 'TO'] },
    { header: 'Sender', aliases: ['Sender', 'From'] },
    { header: 'Name', aliases: ['Name', 'Full Name'] },
    { header: 'Username', aliases: ['Username', 'User Name'] }
  ]);

  risCoreEnsureColumnsByAliases_(clientSheet, [
    { header: 'Recipients', aliases: ['Recipients', 'Receipients', 'Recipient', 'Email', 'Email Address', 'TO'] },
    { header: 'Sender', aliases: ['Sender', 'From'] },
    { header: 'CC', aliases: ['CC', 'Cc', 'Carbon Copy'] },
    { header: 'Subject', aliases: ['Subject', 'Email Subject'] }
  ]);
}

function risCoreGetConfiguredSheet_(ss, name, createMissingSheets) {
  return createMissingSheets ? risCoreGetOrCreateSheet_(ss, name) : risCoreGetRequiredSheet_(ss, name);
}

function risCoreGetRequiredSheet_(ss, name) {
  const sheet = ss.getSheetByName(name);
  if (!sheet) {
    throw new Error('Required sheet not found: ' + name + '. Run RIS Portal > Setup required sheets once, or create the tab manually.');
  }
  return sheet;
}

function risCoreGetOrCreateSheet_(ss, name) {
  return ss.getSheetByName(name) || ss.insertSheet(name);
}

function risCoreEnsureColumns_(sheet, headers) {
  if (sheet.getLastRow() === 0) {
    sheet.getRange(1, 1, 1, headers.length).setValues([headers]);
    return;
  }

  const width = Math.max(sheet.getLastColumn(), 1);
  const current = sheet.getRange(1, 1, 1, width).getValues()[0];
  const normalized = current.map(risCoreNormalizeHeader_);
  const missing = headers.filter(function(header) {
    return normalized.indexOf(risCoreNormalizeHeader_(header)) === -1;
  });

  if (missing.length > 0) {
    sheet.getRange(1, sheet.getLastColumn() + 1, 1, missing.length).setValues([missing]);
  }
}

function risCoreEnsureColumnsByAliases_(sheet, specs) {
  if (sheet.getLastRow() === 0) {
    sheet.getRange(1, 1, 1, specs.length).setValues([specs.map(function(spec) { return spec.header; })]);
    return;
  }

  const width = Math.max(sheet.getLastColumn(), 1);
  const current = sheet.getRange(1, 1, 1, width).getValues()[0];
  const missing = specs.filter(function(spec) {
    return !risFindHeaderColumn_(current, spec.aliases || [spec.header]);
  }).map(function(spec) {
    return spec.header;
  });

  if (missing.length > 0) {
    sheet.getRange(1, sheet.getLastColumn() + 1, 1, missing.length).setValues([missing]);
  }
}

function risCoreGetHeaderInfo_(sheet, defaultHeaders, aliases, updateHeaders) {
  if (updateHeaders !== false) risCoreEnsureColumns_(sheet, defaultHeaders);
  const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];
  const columns = {};
  Object.keys(aliases).forEach(function(field) {
    columns[field] = risFindHeaderColumn_(headers, aliases[field]);
  });
  return { headerRow: 1, headers: headers, columns: columns };
}

function risCoreAppendRecord_(sheet, defaultHeaders, aliases, fieldOrder, record) {
  const info = risCoreGetHeaderInfo_(sheet, defaultHeaders, aliases);
  const row = new Array(sheet.getLastColumn()).fill('');
  fieldOrder.forEach(function(field) {
    if (info.columns[field]) row[info.columns[field] - 1] = record[field] === undefined ? '' : record[field];
  });
  sheet.appendRow(row);
}

function risCoreReadRecords_(sheet, defaultHeaders, aliases, fieldOrder) {
  const info = risCoreGetHeaderInfo_(sheet, defaultHeaders, aliases);
  if (sheet.getLastRow() <= 1) return [];

  return sheet.getRange(2, 1, sheet.getLastRow() - 1, sheet.getLastColumn()).getValues().map(function(row, index) {
    const record = { rowNumber: index + 2 };
    fieldOrder.forEach(function(field) {
      record[field] = info.columns[field] ? row[info.columns[field] - 1] : '';
    });
    return record;
  });
}

function risCoreUpdateRecordFields_(sheet, rowNumber, defaultHeaders, aliases, valuesByField) {
  const info = risCoreGetHeaderInfo_(sheet, defaultHeaders, aliases);
  Object.keys(valuesByField).forEach(function(field) {
    if (info.columns[field]) sheet.getRange(rowNumber, info.columns[field]).setValue(valuesByField[field]);
  });
}

function risCoreGetRisBundle_(risNoOrRecordId) {
  const ss = risCoreGetTransactionsSpreadsheet_();
  risCoreEnsureTransactionSheets_(ss, RIS_CONFIG.autoCreateSheets);
  const entriesSheet = risCoreGetRequiredSheet_(ss, RIS_CONFIG.entriesSheetName);
  const itemsSheet = risCoreGetRequiredSheet_(ss, RIS_CONFIG.itemsSheetName);
  const key = risCoreNormalizeText_(risNoOrRecordId);

  const entry = risCoreReadRecords_(entriesSheet, RIS_ENTRIES_DEFAULT_HEADERS, RIS_ENTRIES_ALIASES, RIS_ENTRIES_FIELD_ORDER).find(function(record) {
    return risCoreNormalizeText_(record.risNo) === key || risCoreNormalizeText_(record.recordId) === key;
  });
  if (!entry) throw new Error('RIS record was not found: ' + risNoOrRecordId);

  const entryRisNo = risCoreNormalizeText_(entry.risNo);
  const entryRecordId = risCoreNormalizeText_(entry.recordId);
  const items = risCoreReadRecords_(itemsSheet, RIS_ITEMS_DEFAULT_HEADERS, RIS_ITEMS_ALIASES, RIS_ITEMS_FIELD_ORDER).filter(function(item) {
    const itemRisNo = risCoreNormalizeText_(item.risNo);
    const itemRecordId = risCoreNormalizeText_(item.recordId);
    return (entryRisNo && itemRisNo === entryRisNo) ||
      (entryRecordId && itemRecordId === entryRecordId);
  });

  return { ss: ss, entry: entry, items: items, entriesSheet: entriesSheet, itemsSheet: itemsSheet };
}

function risCoreRecoverInventoryDataForItem_(item) {
  if (!item.sourceSheet || !item.sourceRow) return {};

  const source = {
    sourceKey: risSlug_(item.category || item.inventorySource || item.sourceSheet),
    category: item.category || '',
    sourceSpreadsheetId: risNormalizeSpreadsheetId_(item.sourceSpreadsheetId),
    sourceSheetName: item.sourceSheet,
    headerRow: item.sourceHeaderRow || 'auto'
  };
  const ss = risCoreOpenSourceSpreadsheet_(source);
  const sheet = typeof risResolveSourceSheet_ === 'function' ? risResolveSourceSheet_(ss, source) : ss.getSheetByName(source.sourceSheetName);
  if (!sheet) return {};

  const resolvedSource = Object.assign({}, source, { sourceSheetName: sheet.getName() });
  const layout = risGetInventoryLayout_(sheet, resolvedSource);
  const rowNumber = risCoreParseInteger_(item.sourceRow);
  if (!rowNumber) return {};
  return risMapInventoryRow_(sheet.getRange(rowNumber, 1, 1, sheet.getLastColumn()).getValues()[0], layout, resolvedSource, rowNumber);
}

function risCoreValidateActiveUser_(username) {
  const wanted = risCoreNormalizeText_(username);
  if (!wanted) throw new Error('Username is required.');

  const ss = risCoreGetTransactionsSpreadsheet_();
  const sheet = ss.getSheetByName(RIS_CONFIG.adminEmailsSheetName) || ss.getSheetByName(RIS_CONFIG.usersSheetName);
  if (!sheet) throw new Error('Admin Emails sheet was not found.');

  const values = sheet.getDataRange().getValues();
  if (values.length < 2) throw new Error('Admin Emails sheet has no administrators.');
  const headers = values[0];
  const nameCol = risFindHeaderColumn_(headers, ['Name', 'Full Name']);
  const firstNameCol = risFindHeaderColumn_(headers, ['First Name']);
  const lastNameCol = risFindHeaderColumn_(headers, ['Last Name']);
  const usernameCol = risFindHeaderColumn_(headers, ['Username', 'User Name']);
  const recipientCol = risFindHeaderColumn_(headers, ['Recipients', 'Receipients', 'Recipient', 'Email', 'Email Address', 'TO']);
  const senderCol = risFindHeaderColumn_(headers, ['Sender', 'From']);
  const statusCol = risFindHeaderColumn_(headers, ['Status']);
  const userTypeCol = risFindHeaderColumn_(headers, ['User Type', 'Role']);

  if (!usernameCol && !recipientCol && !senderCol) {
    throw new Error('Admin Emails must include Username, Recipients, Receipients, or Sender columns.');
  }

  for (let i = 1; i < values.length; i++) {
    const row = values[i];
    const rowUsername = usernameCol ? row[usernameCol - 1] : '';
    const rowRecipient = recipientCol ? row[recipientCol - 1] : '';
    const rowSender = senderCol ? row[senderCol - 1] : '';
    const rowKeys = [rowUsername, rowRecipient, rowSender];
    const matches = rowKeys.some(function(value) {
      return risCoreNormalizeText_(value) === wanted;
    });

    if (matches) {
      const statusText = risCoreNormalizeText_(statusCol ? row[statusCol - 1] : 'active');
      if (statusText && !risCoreTruthy_(statusText)) throw new Error('User "' + username + '" is not active.');

      const firstName = firstNameCol ? row[firstNameCol - 1] : '';
      const lastName = lastNameCol ? row[lastNameCol - 1] : '';
      const fullName = String(nameCol ? row[nameCol - 1] : '').trim() ||
        String((firstName || '') + ' ' + (lastName || '')).trim() ||
        String(rowUsername || username).trim();

      return {
        fullName: fullName,
        username: String(rowUsername || username).trim(),
        userType: userTypeCol ? row[userTypeCol - 1] : 'Admin',
        status: statusText || 'active'
      };
    }
  }

  throw new Error('Username was not found in Admin Emails: ' + username);
}

function risCoreReadEmailRecipients_(ss) {
  const to = [];
  const cc = [];

  risCoreReadRecipientsFromSheet_(ss.getSheetByName(RIS_CONFIG.adminEmailsSheetName), to, cc);
  risCoreReadRecipientsFromSheet_(ss.getSheetByName(RIS_CONFIG.clientEmailsSheetName), to, cc);

  (RIS_CONFIG.legacyEmailsSheetNames || []).forEach(function(name) {
    risCoreReadRecipientsFromSheet_(ss.getSheetByName(name), to, cc);
  });

  return { to: risCoreUnique_(to), cc: risCoreUnique_(cc) };
}

function risCoreReadRecipientsFromSheet_(sheet, to, cc) {
  if (!sheet || sheet.getLastRow() < 2) return;

  const values = sheet.getDataRange().getValues();
  const headers = values[0];
  const toCol = risFindHeaderColumn_(headers, ['Recipients', 'Receipients', 'Recipient', 'TO', 'To', 'Email', 'Email Address']);
  const ccCol = risFindHeaderColumn_(headers, ['CC', 'Cc', 'Carbon Copy']);

  values.slice(1).forEach(function(row) {
    if (toCol) risCoreSplitEmailList_(row[toCol - 1]).forEach(function(email) { to.push(email); });
    if (ccCol) risCoreSplitEmailList_(row[ccCol - 1]).forEach(function(email) { cc.push(email); });
  });
}

function risCoreSplitEmailList_(value) {
  return String(value || '').split(/[;,\n]+/).map(function(email) {
    return email.trim();
  }).filter(String);
}

function risFindHeaderColumn_(headers, aliases) {
  const lookup = {};
  headers.forEach(function(header, index) {
    const key = risCoreNormalizeHeader_(header);
    if (key && !lookup[key]) lookup[key] = index + 1;
  });

  for (let i = 0; i < aliases.length; i++) {
    const key = risCoreNormalizeHeader_(aliases[i]);
    if (lookup[key]) return lookup[key];
  }
  return 0;
}

function risCell_(row, column) {
  return column ? row[column - 1] : '';
}

function risRequiredText_(value, label) {
  const text = String(value || '').trim();
  if (!text) throw new Error(label + ' is required.');
  return text;
}

function risCleanText_(value) {
  return String(value === null || value === undefined ? '' : value).replace(/\s+/g, ' ').trim();
}

function risCoreNormalizeHeader_(value) {
  return risCleanText_(value).toUpperCase().replace(/[^A-Z0-9]+/g, ' ').trim();
}

function risCoreNormalizeText_(value) {
  return risCleanText_(value).toLowerCase();
}

function risCoreTruthy_(value) {
  return value === true || ['true', 'yes', 'y', '1', 'enabled', 'active'].indexOf(risCoreNormalizeText_(value)) !== -1;
}

function risSlug_(value) {
  return risCoreNormalizeText_(value).replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

function risNormalizeSpreadsheetId_(value) {
  const raw = String(value || '').trim();
  return !raw || /^same$/i.test(raw) ? 'same' : raw;
}

function risCoreParseNumber_(value) {
  if (typeof value === 'number') return isFinite(value) ? value : 0;
  const number = Number(String(value || '').replace(/,/g, '').trim());
  return isFinite(number) ? number : 0;
}

function risCoreParseInteger_(value) {
  const number = parseInt(value, 10);
  return isFinite(number) ? number : 0;
}

function risCoreParseDate_(value) {
  if (value instanceof Date) return value;
  if (!value) return null;
  const date = new Date(value);
  return isNaN(date.getTime()) ? null : date;
}

function risCoreDateOnly_(date) {
  return new Date(date.getFullYear(), date.getMonth(), date.getDate());
}

function risCoreDateKey_(value) {
  const date = risCoreParseDate_(value);
  return date ? Utilities.formatDate(date, Session.getScriptTimeZone(), 'yyyy-MM-dd') : '';
}

function risCoreFormatDate_(value) {
  const date = risCoreParseDate_(value);
  return date ? Utilities.formatDate(date, Session.getScriptTimeZone(), 'yyyy-MM-dd') : (value || '');
}

function risCoreMoney_(value) {
  return 'PHP ' + risCoreParseNumber_(value).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function risCoreEscapeHtml_(value) {
  return String(value === null || value === undefined ? '' : value).replace(/[&<>"']/g, function(char) {
    return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' })[char];
  });
}

function risCoreUnique_(values) {
  const seen = {};
  return values.filter(function(value) {
    const text = String(value || '').trim();
    const key = text.toLowerCase();
    if (!text || seen[key]) return false;
    seen[key] = true;
    return true;
  });
}

function risCoreErrorMessage_(error) {
  return error && (error.message || error.toString()) || 'Unknown error';
}
