// ==========================================
// RIS SHARED HELPERS
// ==========================================

const RIS_ENTRIES_DEFAULT_HEADERS = [
  'Timestamp', 'Record ID', 'RIS No.', 'Category', 'Inventory Source', 'Date', 'Requestor Program',
  'Requestor Email', 'Delivery Location / Office', 'Requested By', 'Approved By', 'Issued By',
  'Received By', 'Purpose', 'Grand Total', 'RIS Status', 'PDF URL', 'PDF Generated At',
  'PDF Generated By', 'Excel URL', 'Excel Generated At', 'Excel Generated By'
];

const RIS_ENTRIES_FIELD_ORDER = [
  'timestamp', 'recordId', 'risNo', 'category', 'inventorySource', 'deliveryDate', 'requestorProgram',
  'requestorEmail', 'deliveryLocation', 'requestedBy', 'approvedBy', 'issuedBy', 'receivedBy',
  'purpose', 'grandTotal', 'risStatus', 'pdfUrl', 'pdfGeneratedAt', 'pdfGeneratedBy',
  'excelUrl', 'excelGeneratedAt', 'excelGeneratedBy'
];

const RIS_ENTRIES_ALIASES = {
  timestamp: ['Timestamp', 'Date Submitted', 'Submitted At'],
  recordId: ['Record ID', 'RecordId'],
  risNo: ['RIS No.', 'RIS No', 'RIS Number'],
  category: ['Category', 'RIS Category'],
  inventorySource: ['Inventory Source', 'Source', 'Source Sheet'],
  deliveryDate: ['Date', 'Delivery Date', 'RIS Date'],
  requestorProgram: ['Requestor Program', 'Program', 'End User'],
  requestorEmail: ['Requestor Email', 'Email', 'Email Address'],
  deliveryLocation: ['Delivery Location / Office', 'Delivery Location', 'Office'],
  requestedBy: ['Requested By'],
  approvedBy: ['Approved By'],
  issuedBy: ['Issued By'],
  receivedBy: ['Received By'],
  purpose: ['Purpose'],
  grandTotal: ['Grand Total', 'Total Request Amount', 'Total Amount'],
  risStatus: ['RIS Status', 'Status'],
  pdfUrl: ['PDF URL', 'RIS PDF URL', 'PDF Link'],
  pdfGeneratedAt: ['PDF Generated At', 'RIS PDF Generated At'],
  pdfGeneratedBy: ['PDF Generated By', 'RIS PDF Generated By'],
  excelUrl: ['Excel URL', 'RIS Excel URL', 'Excel Link'],
  excelGeneratedAt: ['Excel Generated At', 'RIS Excel Generated At'],
  excelGeneratedBy: ['Excel Generated By', 'RIS Excel Generated By']
};

const RIS_ITEMS_DEFAULT_HEADERS = [
  'Timestamp', 'Item ID', 'Record ID', 'RIS No.', 'Category', 'Inventory Source', 'Item Code',
  'Item Description', 'UOM', 'PO/PTR Number', 'Supplier', 'Batch / Lot No.', 'Expiry Date',
  'Current SOH', 'Qty Requested', 'Issued Qty', 'Unit Cost', 'Total Cost', 'Remarks',
  'Source Spreadsheet ID', 'Source Sheet', 'Source Row', 'Source Header Row'
];

const RIS_ITEMS_FIELD_ORDER = [
  'timestamp', 'itemId', 'recordId', 'risNo', 'category', 'inventorySource', 'itemCode',
  'itemDescription', 'uom', 'poNumber', 'supplier', 'batch', 'expiry', 'currentSoh',
  'qtyRequested', 'issuedQty', 'unitCost', 'totalCost', 'remarks', 'sourceSpreadsheetId',
  'sourceSheet', 'sourceRow', 'sourceHeaderRow'
];

const RIS_ITEMS_ALIASES = {
  timestamp: ['Timestamp', 'Date Submitted', 'Submitted At'],
  itemId: ['Item ID', 'ItemId'],
  recordId: ['Record ID', 'RecordId'],
  risNo: ['RIS No.', 'RIS No', 'RIS Number'],
  category: ['Category', 'RIS Category'],
  inventorySource: ['Inventory Source', 'Source'],
  itemCode: ['Item Code'],
  itemDescription: ['Item Description', 'Description'],
  uom: ['UOM', 'Unit of Measure', 'Unit of Measurement'],
  poNumber: ['PO/PTR Number', 'PO / PTR', 'PO / PTR Number', 'Purchase Order Number', 'PO Number'],
  supplier: ['Supplier'],
  batch: ['Batch / Lot No.', 'Batch / Lot No', 'Batch', 'Lot Number', 'Batch / Lot Number'],
  expiry: ['Expiry Date', 'Expiration Date'],
  currentSoh: ['Current SOH', 'Stock On Hand', 'SOH', 'Stock Available', 'Physical Count'],
  qtyRequested: ['Qty Requested', 'Quantity Requested', 'Qty Req'],
  issuedQty: ['Issued Qty', 'Issued Quantity'],
  unitCost: ['Unit Cost'],
  totalCost: ['Total Cost', 'Total Amount', 'Total Price'],
  remarks: ['Remarks'],
  sourceSpreadsheetId: ['Source Spreadsheet ID'],
  sourceSheet: ['Source Sheet', 'Inventory Source Sheet'],
  sourceRow: ['Source Row', 'Inventory Source Row'],
  sourceHeaderRow: ['Source Header Row']
};

function risCoreGetTransactionsSpreadsheet_() {
  if (RIS_CONFIG.transactionsSheetId && RIS_CONFIG.transactionsSheetId.indexOf('PASTE_') !== 0) {
    return SpreadsheetApp.openById(RIS_CONFIG.transactionsSheetId);
  }
  return SpreadsheetApp.getActiveSpreadsheet();
}

function risCoreOpenSourceSpreadsheet_(source) {
  const sourceId = source && source.sourceSpreadsheetId && source.sourceSpreadsheetId !== 'same'
    ? source.sourceSpreadsheetId
    : RIS_CONFIG.inventorySheetId;
  if (sourceId && sourceId.indexOf('PASTE_') !== 0) return SpreadsheetApp.openById(sourceId);
  return risCoreGetTransactionsSpreadsheet_();
}

function risCoreEnsureTransactionSheets_(ss) {
  risCoreEnsureColumns_(risCoreGetOrCreateSheet_(ss, RIS_CONFIG.entriesSheetName), RIS_ENTRIES_DEFAULT_HEADERS);
  risCoreEnsureColumns_(risCoreGetOrCreateSheet_(ss, RIS_CONFIG.itemsSheetName), RIS_ITEMS_DEFAULT_HEADERS);
  risCoreEnsureColumns_(risCoreGetOrCreateSheet_(ss, 'Emails'), ['TO', 'CC']);
  risCoreEnsureColumns_(risCoreGetOrCreateSheet_(ss, RIS_CONFIG.usersSheetName), ['First Name', 'Last Name', 'Username', 'User Type', 'Status']);
  risCoreGetOrCreateSheet_(ss, RIS_CONFIG.holidaysSheetName);
}

function risCoreGetOrCreateSheet_(ss, name) {
  return ss.getSheetByName(name) || ss.insertSheet(name);
}

function risCoreEnsureColumns_(sheet, headers) {
  if (sheet.getLastRow() === 0) {
    sheet.getRange(1, 1, 1, headers.length).setValues([headers]);
    return;
  }

  const width = Math.max(sheet.getLastColumn(), 1);
  const current = sheet.getRange(1, 1, 1, width).getValues()[0];
  const normalized = current.map(risCoreNormalizeHeader_);
  const missing = headers.filter(function(header) {
    return normalized.indexOf(risCoreNormalizeHeader_(header)) === -1;
  });

  if (missing.length > 0) {
    sheet.getRange(1, sheet.getLastColumn() + 1, 1, missing.length).setValues([missing]);
  }
}

function risCoreGetHeaderInfo_(sheet, defaultHeaders, aliases) {
  risCoreEnsureColumns_(sheet, defaultHeaders);
  const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];
  const columns = {};
  Object.keys(aliases).forEach(function(field) {
    columns[field] = risFindHeaderColumn_(headers, aliases[field]);
  });
  return { headerRow: 1, headers: headers, columns: columns };
}

function risCoreAppendRecord_(sheet, defaultHeaders, aliases, fieldOrder, record) {
  const info = risCoreGetHeaderInfo_(sheet, defaultHeaders, aliases);
  const row = new Array(sheet.getLastColumn()).fill('');
  fieldOrder.forEach(function(field) {
    if (info.columns[field]) row[info.columns[field] - 1] = record[field] === undefined ? '' : record[field];
  });
  sheet.appendRow(row);
}

function risCoreReadRecords_(sheet, defaultHeaders, aliases, fieldOrder) {
  const info = risCoreGetHeaderInfo_(sheet, defaultHeaders, aliases);
  if (sheet.getLastRow() <= 1) return [];

  return sheet.getRange(2, 1, sheet.getLastRow() - 1, sheet.getLastColumn()).getValues().map(function(row, index) {
    const record = { rowNumber: index + 2 };
    fieldOrder.forEach(function(field) {
      record[field] = info.columns[field] ? row[info.columns[field] - 1] : '';
    });
    return record;
  });
}

function risCoreUpdateRecordFields_(sheet, rowNumber, defaultHeaders, aliases, valuesByField) {
  const info = risCoreGetHeaderInfo_(sheet, defaultHeaders, aliases);
  Object.keys(valuesByField).forEach(function(field) {
    if (info.columns[field]) sheet.getRange(rowNumber, info.columns[field]).setValue(valuesByField[field]);
  });
}

function risCoreGetRisBundle_(risNoOrRecordId) {
  const ss = risCoreGetTransactionsSpreadsheet_();
  risCoreEnsureTransactionSheets_(ss);
  const entriesSheet = ss.getSheetByName(RIS_CONFIG.entriesSheetName);
  const itemsSheet = ss.getSheetByName(RIS_CONFIG.itemsSheetName);
  const key = risCoreNormalizeText_(risNoOrRecordId);

  const entry = risCoreReadRecords_(entriesSheet, RIS_ENTRIES_DEFAULT_HEADERS, RIS_ENTRIES_ALIASES, RIS_ENTRIES_FIELD_ORDER).find(function(record) {
    return risCoreNormalizeText_(record.risNo) === key || risCoreNormalizeText_(record.recordId) === key;
  });
  if (!entry) throw new Error('RIS record was not found: ' + risNoOrRecordId);

  const items = risCoreReadRecords_(itemsSheet, RIS_ITEMS_DEFAULT_HEADERS, RIS_ITEMS_ALIASES, RIS_ITEMS_FIELD_ORDER).filter(function(item) {
    return risCoreNormalizeText_(item.risNo) === risCoreNormalizeText_(entry.risNo) ||
      risCoreNormalizeText_(item.recordId) === risCoreNormalizeText_(entry.recordId);
  });

  return { ss: ss, entry: entry, items: items, entriesSheet: entriesSheet, itemsSheet: itemsSheet };
}

function risCoreRecoverInventoryDataForItem_(item) {
  if (!item.sourceSheet || !item.sourceRow) return {};

  const source = {
    sourceKey: risSlug_(item.category || item.inventorySource || item.sourceSheet),
    category: item.category || '',
    sourceSpreadsheetId: risNormalizeSpreadsheetId_(item.sourceSpreadsheetId),
    sourceSheetName: item.sourceSheet,
    headerRow: item.sourceHeaderRow || 'auto'
  };
  const ss = risCoreOpenSourceSpreadsheet_(source);
  const sheet = ss.getSheetByName(source.sourceSheetName);
  if (!sheet) return {};

  const layout = risGetInventoryLayout_(sheet, source);
  const rowNumber = risCoreParseInteger_(item.sourceRow);
  if (!rowNumber) return {};
  return risMapInventoryRow_(sheet.getRange(rowNumber, 1, 1, sheet.getLastColumn()).getValues()[0], layout, source, rowNumber);
}

function risCoreValidateActiveUser_(username) {
  const ss = risCoreGetTransactionsSpreadsheet_();
  const sheet = ss.getSheetByName(RIS_CONFIG.usersSheetName);
  if (!sheet) throw new Error('Users sheet was not found.');

  const values = sheet.getDataRange().getValues();
  if (values.length < 2) throw new Error('Users sheet has no users.');
  const headers = values[0];
  const firstNameCol = risFindHeaderColumn_(headers, ['First Name']);
  const lastNameCol = risFindHeaderColumn_(headers, ['Last Name']);
  const usernameCol = risFindHeaderColumn_(headers, ['Username']);
  const statusCol = risFindHeaderColumn_(headers, ['Status']);
  const wanted = risCoreNormalizeText_(username);

  if (!usernameCol || !statusCol) throw new Error('Users sheet must include Username and Status columns.');

  for (let i = 1; i < values.length; i++) {
    const row = values[i];
    if (risCoreNormalizeText_(row[usernameCol - 1]) === wanted) {
      if (risCoreNormalizeText_(row[statusCol - 1]) !== 'active') throw new Error('User "' + username + '" is not active.');
      const fullName = String((firstNameCol ? row[firstNameCol - 1] : '') + ' ' + (lastNameCol ? row[lastNameCol - 1] : '')).trim() || username;
      return { fullName: fullName, username: username, status: row[statusCol - 1] };
    }
  }

  throw new Error('Username was not found: ' + username);
}

function risCoreReadEmailRecipients_(ss) {
  let sheet = null;
  RIS_CONFIG.emailsSheetNames.some(function(name) {
    sheet = ss.getSheetByName(name);
    return !!sheet;
  });
  if (!sheet || sheet.getLastRow() < 2) return { to: [], cc: [] };

  const values = sheet.getDataRange().getValues();
  const toCol = risFindHeaderColumn_(values[0], ['TO', 'To']);
  const ccCol = risFindHeaderColumn_(values[0], ['CC', 'Cc']);
  const to = [];
  const cc = [];

  values.slice(1).forEach(function(row) {
    if (toCol && row[toCol - 1]) to.push(String(row[toCol - 1]).trim());
    if (ccCol && row[ccCol - 1]) cc.push(String(row[ccCol - 1]).trim());
  });

  return { to: risCoreUnique_(to), cc: risCoreUnique_(cc) };
}

function risFindHeaderColumn_(headers, aliases) {
  const lookup = {};
  headers.forEach(function(header, index) {
    const key = risCoreNormalizeHeader_(header);
    if (key && !lookup[key]) lookup[key] = index + 1;
  });

  for (let i = 0; i < aliases.length; i++) {
    const key = risCoreNormalizeHeader_(aliases[i]);
    if (lookup[key]) return lookup[key];
  }
  return 0;
}

function risCell_(row, column) {
  return column ? row[column - 1] : '';
}

function risRequiredText_(value, label) {
  const text = String(value || '').trim();
  if (!text) throw new Error(label + ' is required.');
  return text;
}

function risCleanText_(value) {
  return String(value === null || value === undefined ? '' : value).replace(/\s+/g, ' ').trim();
}

function risCoreNormalizeHeader_(value) {
  return risCleanText_(value).toUpperCase().replace(/[^A-Z0-9]+/g, ' ').trim();
}

function risCoreNormalizeText_(value) {
  return risCleanText_(value).toLowerCase();
}

function risCoreTruthy_(value) {
  return value === true || ['true', 'yes', 'y', '1', 'enabled', 'active'].indexOf(risCoreNormalizeText_(value)) !== -1;
}

function risSlug_(value) {
  return risCoreNormalizeText_(value).replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

function risNormalizeSpreadsheetId_(value) {
  const raw = String(value || '').trim();
  return !raw || /^same$/i.test(raw) ? 'same' : raw;
}

function risCoreParseNumber_(value) {
  if (typeof value === 'number') return isFinite(value) ? value : 0;
  const number = Number(String(value || '').replace(/,/g, '').trim());
  return isFinite(number) ? number : 0;
}

function risCoreParseInteger_(value) {
  const number = parseInt(value, 10);
  return isFinite(number) ? number : 0;
}

function risCoreParseDate_(value) {
  if (value instanceof Date) return value;
  if (!value) return null;
  const date = new Date(value);
  return isNaN(date.getTime()) ? null : date;
}

function risCoreDateOnly_(date) {
  return new Date(date.getFullYear(), date.getMonth(), date.getDate());
}

function risCoreDateKey_(value) {
  const date = risCoreParseDate_(value);
  return date ? Utilities.formatDate(date, Session.getScriptTimeZone(), 'yyyy-MM-dd') : '';
}

function risCoreFormatDate_(value) {
  const date = risCoreParseDate_(value);
  return date ? Utilities.formatDate(date, Session.getScriptTimeZone(), 'yyyy-MM-dd') : (value || '');
}

function risCoreMoney_(value) {
  return 'PHP ' + risCoreParseNumber_(value).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function risCoreEscapeHtml_(value) {
  return String(value === null || value === undefined ? '' : value).replace(/[&<>"']/g, function(char) {
    return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' })[char];
  });
}

function risCoreUnique_(values) {
  const seen = {};
  return values.filter(function(value) {
    const text = String(value || '').trim();
    const key = text.toLowerCase();
    if (!text || seen[key]) return false;
    seen[key] = true;
    return true;
  });
}

function risCoreErrorMessage_(error) {
  return error && (error.message || error.toString()) || 'Unknown error';
}
